### ISSUE TITLE
hi，I want to apply your core in 1D CNN

### ISSUE THREAD

**Issue by 1448643857** [kimhc6028/soft-decision-tree#7]
where code should I to change?thank u

**Comment by kimhc6028** [comment]
hi, 
the only part using "neural network" is 
https://github.com/kimhc6028/soft-decision-tree/blob/abe7a9b1690490cb450793d3417c7078ef1a6df1/model.py#L16

I don't get how would you apply 1d cnn for this network, but I would recommend to start from line above.

**Comment by 1448643857** [comment]
I'll read your code first, and then see if it can be applied to my problem. I may ask you later. Thank you.
