### ISSUE TITLE
where is the 0.5 test  ?

### ISSUE THREAD

**Issue by Oussamab21** [kimhc6028/soft-decision-tree#8]
Thank you for sharing this code I was wondering why did you comment that forward section in soft decision tree and why you are not using the 0.5 test for left or right nodes ??

just another question output dimension in args is the number of classes right?

best regards

**Comment by kimhc6028** [comment]
Hello, for the first question, I wrote these codes 2 years ago so that I forgot details of paper. Can you point out where I can find descriptions regarding "0.5 test"?

For the second question, if my memory is correct, yes, output_dim is number of classes

**Comment by Oussamab21** [comment]
thank you for your reply : 
the first question I mean in the paper it was stated that you go left(left node ) or right (right node ) if the probability is more (res less) then 0.5 so I see that you coded that in choose next function but you commented that forward function in SDT class (that is responsible for calling it ) so I wonder why ?

for the second class if I want to apply this program on a data set that is already contain only 1 and 0 (no need for one hot encoding ) that contains 2 classes (0 and 1 ) what should I change ( I mean I won't need target.onehot encoding so should I keep output to 2 ?

**Comment by Oussamab21** [comment]
Dear kim 
I used another data set and it always predict one class even with almost balanced data sets don't you think I am doubting that the loss function is the responsible for that since the output tensor always have the same value for the whole batch ?
regards

**Comment by kimhc6028** [comment]
Isn't select_next(self, x) doing such thing? It seems like this function computes probability first, and selects left node if the probability is below 0.5.
https://github.com/kimhc6028/soft-decision-tree/blob/master/model.py#L48

For the second question, isn't it enough to set input_dim and output_dim as dataset you wanted?
It depends on dataset you are trying with, but how about first trying it with mnist with 2 classes (i.e., only using images with label of 0 and 1). This will make things much easier. If it works with mnist with 2 classes, then you can just modify your dataset to fit in it.

**Comment by Oussamab21** [comment]
Thank you for your reply I tried doing so for the second question but your model in some how only predict 1 class in all cases don't you maybe think that the loss function performs badly when the features are binarized ? all the features are 0 or 1 .
